// MIT License
// Copyright (c) 2016 Geometry Gym Pty Ltd

// Permission is hereby granted, free of charge, to any person obtaining a copy of this software 
// and associated documentation files (the "Software"), to deal in the Software without restriction, 
// including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
// subject to the following conditions:

// The above copyright notice and this permission notice shall be included in all copies or substantial 
// portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT 
// LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

using System; 
using System.Reflection; 
 
namespace GeometryGym.Ifc
{
	public enum ShapeRepresentationType
	{
		Curve2D, Annotation2D, GeometricSet, GeometricCurveSet, SurfaceModel, SolidModel, SweptSolid, CSG, Clipping, AdvancedSweptSolid, Brep, BoundingBox, SectionedSpine, MappedRepresentation,
		[VersionAdded(ReleaseVersion.IFC4)] Point, [VersionAdded(ReleaseVersion.IFC4)] PointCloud, [VersionAdded(ReleaseVersion.IFC4)] Curve, [VersionAdded(ReleaseVersion.IFC4)] Curve3D,
		[VersionAdded(ReleaseVersion.IFC4)] Surface, [VersionAdded(ReleaseVersion.IFC4)] Surface2D, [VersionAdded(ReleaseVersion.IFC4)] Surface3D, [VersionAdded(ReleaseVersion.IFC4)] FillArea,
		[VersionAdded(ReleaseVersion.IFC4)] Text, [VersionAdded(ReleaseVersion.IFC4)] Tessellation, [VersionAdded(ReleaseVersion.IFC4)] AdvancedBrep, [VersionAdded(ReleaseVersion.IFC4)] LightSource
	};

	[VersionAdded(ReleaseVersion.IFC4)]
	public enum IfcActionRequestTypeEnum { EMAIL, FAX, PHONE, POST, VERBAL, USERDEFINED, NOTDEFINED };
	[VersionAdded(ReleaseVersion.IFC2x2)]
	public enum IfcActionSourceTypeEnum { DEAD_LOAD_G, COMPLETION_G1, LIVE_LOAD_Q, SNOW_S, WIND_W, PRESTRESSING_P, SETTLEMENT_U, TEMPERATURE_T, EARTHQUAKE_E, FIRE, IMPULSE, IMPACT, TRANSPORT, ERECTION, PROPPING, SYSTEM_IMPERFECTION, SHRINKAGE, CREEP, LACK_OF_FIT, BUOYANCY, ICE, CURRENT, WAVE, RAIN, BRAKES, USERDEFINED, NOTDEFINED };
	[VersionAdded(ReleaseVersion.IFC2x2)]
	public enum IfcActionTypeEnum { PERMANENT_G, VARIABLE_Q, EXTRAORDINARY_A, USERDEFINED, NOTDEFINED };
	//[VersionAdded(ReleaseVersion.IFC2_0)]
	public enum IfcActuatorTypeEnum { ELECTRICACTUATOR, HANDOPERATEDACTUATOR, HYDRAULICACTUATOR, PNEUMATICACTUATOR, THERMOSTATICACTUATOR, USERDEFINED, NOTDEFINED };
	public enum IfcAddressTypeEnum { OFFICE, SITE, HOME, DISTRIBUTIONPOINT, USERDEFINED, NOTDEFINED };
	[Obsolete("DEPRECEATED IFC4", false)]
	public enum IfcAheadOrBehind { AHEAD, BEHIND }; //OBSELETE IFC4
	public enum IfcAirTerminalBoxTypeEnum { CONSTANTFLOW, VARIABLEFLOWPRESSUREDEPENDANT, VARIABLEFLOWPRESSUREINDEPENDANT, USERDEFINED, NOTDEFINED };
	public enum IfcAirTerminalTypeEnum { GRILLE, REGISTER, DIFFUSER, LOUVRE, USERDEFINED, NOTDEFINED, EYEBALL, IRIS, LINEARGRILLE, LINEARDIFFUSER }; //IFC4 DELETED
	public enum IfcAirToAirHeatRecoveryTypeEnum { FIXEDPLATECOUNTERFLOWEXCHANGER, FIXEDPLATECROSSFLOWEXCHANGER, FIXEDPLATEPARALLELFLOWEXCHANGER, ROTARYWHEEL, RUNAROUNDCOILLOOP, HEATPIPE, TWINTOWERENTHALPYRECOVERYLOOPS, THERMOSIPHONSEALEDTUBEHEATEXCHANGERS, THERMOSIPHONCOILTYPEHEATEXCHANGERS, USERDEFINED, NOTDEFINED };
	public enum IfcAlarmTypeEnum { BELL, BREAKGLASSBUTTON, LIGHT, MANUALPULLBOX, SIREN, WHISTLE, USERDEFINED, NOTDEFINED };
	public enum IfcAlignmentTypeEnum { USERDEFINED, NOTDEFINED };
	public enum IfcAnalysisModelTypeEnum { IN_PLANE_LOADING_2D, OUT_PLANE_LOADING_2D, LOADING_3D, USERDEFINED, NOTDEFINED };
	public enum IfcAnalysisTheoryTypeEnum { FIRST_ORDER_THEORY, SECOND_ORDER_THEORY, THIRD_ORDER_THEORY, FULL_NONLINEAR_THEORY, USERDEFINED, NOTDEFINED };
	public enum IfcArithmeticOperatorEnum { ADD, DIVIDE, MULTIPLY, SUBTRACT,NONE }; //GG ADDED NONE
	public enum IfcAssemblyPlaceEnum { SITE, FACTORY, NOTDEFINED };
	public enum IfcAudioVisualApplianceTypeEnum { AMPLIFIER, CAMERA, DISPLAY, MICROPHONE, PLAYER, PROJECTOR, RECEIVER, SPEAKER, SWITCHER, TELEPHONE, TUNER, USERDEFINED, NOTDEFINED };
	public enum IfcBeamTypeEnum { BEAM, HOLLOWCORE, JOIST, LINTEL, SPANDREL, T_BEAM, USERDEFINED, NOTDEFINED };
	public enum IfcBenchmarkEnum { GREATERTHAN, GREATERTHANOREQUALTO, LESSTHAN, LESSTHANOREQUALTO, EQUALTO, NOTEQUALTO, INCLUDES, NOTINCLUDES, INCLUDEDIN, NOTINCLUDEDIN };
	public enum IfcBoilerTypeEnum { WATER, STEAM, USERDEFINED, NOTDEFINED };
	public enum IfcBooleanOperator { UNION, INTERSECTION, DIFFERENCE };
	public enum IfcBridgeContactType { GLUE, RIVET, CONNECTOR, WELD, RESUMPTION_OF_CONCRETE, SLIDING }; //IFC5
	public enum IfcBridgeMechanicalRoleType { LONGITUDINAL, TRANSVERSAL, COMPLETE, NONE, UNDEFINED }; //IFC5
	public enum IfcBridgePrismaticElementType { UNICELLULAR_MONO_BOX_GIRDER, MULTICELLULAR_MONO_BOX_GIRDER, UNICELLULAR_MULTI_BOX_GIRDER, MULTICELLULAR_MULTI_BOX_GIRDER, DOUBLE_BEAM_RIBBED_SLAB, MULTI_BEAM_RIBBED_SLAB, MASSIVE_SECTION_ELEMENT, HOLLOW_SECTION_ELEMENT, SOLID_SLAB, HOLLOW_SLAB, SLAB_WITH_BROAD_CANTILEVER, MASTER_BEAM, LONGITUDINAL_GIRDER, RIGIDITY_BEAM, BRACING, UPPER_FLANGE, LOWER_FLANGE, UPPER_FOOTING, LOWER_FOOTING, WEB, FLOORING_SHEET, BOTTOM_SHEET, KERB_SHEET, CANTILEVER_SHEET, PAVEMENT_SHEET, AUGET, LONGITUDINAL_WEB_STIFFENER, RAKER, TRANSVERSE_GIRDER, DEFLECTER, TRANSVERSE_MEMBER, TRANSVERSE, DIAGONALE, JAMB, TENSION_MEMBER, BONDING_BAR, TRANSVERSAL_STIFFENER, STIFFENER_FOOTING, TENDON }; //IFC5
	public enum IfcBridgeSegmentType { TYPICAL_SEGMENT, PIER_SEGMENT, PIECE, LIFT, ELEMENT, JAMB, PYLON_HEAD, SPAN, CANTILEVER, FINITE_ELEMENT_REFERENCE }; //IFC5
	public enum IfcBridgeStructureElementType { DECK, PIER, SMALL_PIER, PYLON, ARCH, LAUNCHING_NOSE, TEMPORARY_BENT, TRANSVERSE_GIRDER, STRUT, COUNTER_STRUT, CABLE, SUSPENDED_TENDON, SUSPENDER, MOBILE_FALSEWORK, STAYING_MAST, LAUNCHING_BEAM }; //IFC5
	public enum IfcBridgeStructureIndicator { COMPOSITE, COATED, HOMOGENEOUS, OTHER }; //IFC5
	public enum IfcBridgeStructureType { BOX_GIRDER_BRIDGE, ARCHED_BRIDGE, SUSPENSION_BRIDGE, CABLE_STAYED_BRIDGE, GIRDER_BRIDGE, SLAB_BRIDGE, SLAB_BRIDGE_WITH_BROAD_CANTILEVER, BOW_STRING_BRIDGE, LADDER_BRIDGE, FRAMEWORK_BRIDGE, GISCLARD_BRIDGE, PORTAL_BRIDGE }; //IFC5
	public enum IfcBridgeSubPartType { LEFT_WEB, RIGHT_WEB, CENTRAL_WEB, TOP_SLAB, LOWER_SLAB, RIGHT_OVERHANG, LEFT_OVERHANG, UPPER_FLANGE_, LOWER_FLANGE, LOWER_FLOORING, UPPER_FLOORING, MORPHOLOGY_NODE, REFERENCE_FIBRE, BRANCH_WALL }; //IFC5
	public enum IfcBridgeTechnologicalElementType { UNICELLULAR_MONO_BOX_GIRDER, MULTICELLULAR_MONO_BOX_GIRDER, UNICELLULAR_MULTI_BOX_GIRDER, MULTICELLULAR_MULTI_BOX_GIRDER, SOLID_SLAB, HOLLOW_SLAB, SLAB_WITH_BROAD_CANTILEVER, DOUBLE_BEAM_RIBBED_SLAB, MULTI_BEAM_RIBBED_SLAB, MASSIVE_SECTION_ELEMENT, HOLLOW_SECTION_ELEMENT, MARKETED_SECTION_GIRDER, RE_ASSEMBLED_SECTION_GIRDER, TRUSS, LADDER_OR_VIERENDEEL, BOW_STRING }; //IFC5
	public enum IfcBSplineCurveForm { POLYLINE_FORM, CIRCULAR_ARC, ELLIPTIC_ARC, PARABOLIC_ARC, HYPERBOLIC_ARC, UNSPECIFIED };
	public enum IfcBSplineSurfaceForm { PLANE_SURF, CYLINDRICAL_SURF, CONICAL_SURF, SPHERICAL_SURF, TOROIDAL_SURF, SURF_OF_REVOLUTION, RULED_SURF, GENERALISED_CONE, QUADRIC_SURF, SURF_OF_LINEAR_EXTRUSION, UNSPECIFIED };
	public enum IfcBuildingElementPartTypeEnum { INSULATION, PRECASTPANEL, USERDEFINED, NOTDEFINED };
	public enum IfcBuildingElementProxyTypeEnum { COMPLEX, ELEMENT, PARTIAL, PROVISIONFORVOID, PROVISIONFORSPACE, USERDEFINED, NOTDEFINED }; // 1st 3 not used
	public enum IfcBuildingSystemTypeEnum { FENESTRATION, FOUNDATION, LOADBEARING, OUTERSHELL, SHADING, TRANSPORT, USERDEFINED, NOTDEFINED};
	public enum IfcBurnerTypeEnum { USERDEFINED, NOTDEFINED };
	public enum IfcCableCarrierFittingTypeEnum { BEND, CROSS, REDUCER, TEE, USERDEFINED, NOTDEFINED };
	public enum IfcCableCarrierSegmentTypeEnum { CABLELADDERSEGMENT, CABLETRAYSEGMENT, CABLETRUNKINGSEGMENT, CONDUITSEGMENT, USERDEFINED, NOTDEFINED };
	public enum IfcCableFittingTypeEnum { CONNECTOR, ENTRY, EXIT, JUNCTION, TRANSITION, USERDEFINED, NOTDEFINED };
	public enum IfcCableSegmentTypeEnum { CABLESEGMENT, CONDUCTORSEGMENT, USERDEFINED, NOTDEFINED };
	public enum IfcCardinalPointReference { DEFAULT = 0, BOTLEFT = 1, BOTMID = 2, BOTRIGHT = 3, MIDLEFT = 4, MID = 5, MIDRIGHT = 6, TOPLEFT = 7, TOPMID = 8, TOPRIGHT = 9, CENTROID = 10, BOTCENT = 11, LEFTCENT = 12, RIGHTCENT = 13, TOPCENT = 14, SHEARCENT = 15, BOTSHEAR = 16, LEFTSHEAR = 17, RIGHTSHEAR = 18, TOPSHEAR = 19};
	public enum IfcChangeActionEnum { NOCHANGE, MODIFIED, ADDED, DELETED, NOTDEFINED, MODIFIEDADDED, MODIFIEDDELETED }; //IFC4 MODIFIED DELETED
	public enum IfcChillerTypeEnum { AIRCOOLED, WATERCOOLED, HEATRECOVERY, USERDEFINED, NOTDEFINED };
	public enum IfcChimneyTypeEnum { USERDEFINED, NOTDEFINED };
	public enum IfcCoilTypeEnum { DXCOOLINGCOIL, WATERCOOLINGCOIL, STEAMHEATINGCOIL, WATERHEATINGCOIL, ELECTRICHEATINGCOIL, GASHEATINGCOIL, USERDEFINED, NOTDEFINED };
	public enum IfcColumnTypeEnum { COLUMN, USERDEFINED, NOTDEFINED };
	public enum IfcCommunicationsApplianceTypeEnum { ANTENNA, COMPUTER, FAX, GATEWAY, MODEM, NETWORKAPPLIANCE, NETWORKBRIDGE, NETWORKHUB, PRINTER, REPEATER, ROUTER, SCANNER, USERDEFINED, NOTDEFINED };
	public enum IfcComplexPropertyTemplateTypeEnum { P_COMPLEX, Q_COMPLEX, NOTDEFINED };
	public enum IfcCompressorTypeEnum { DYNAMIC, RECIPROCATING, ROTARY, SCROLL, TROCHOIDAL, SINGLESTAGE, BOOSTER, OPENTYPE, HERMETIC, SEMIHERMETIC, WELDEDSHELLHERMETIC, ROLLINGPISTON, ROTARYVANE, SINGLESCREW, TWINSCREW, USERDEFINED, NOTDEFINED };
	public enum IfcCondenserTypeEnum { WATERCOOLEDSHELLTUBE, WATERCOOLEDSHELLCOIL, WATERCOOLEDTUBEINTUBE, WATERCOOLEDBRAZEDPLATE, AIRCOOLED, EVAPORATIVECOOLED, USERDEFINED, NOTDEFINED };
	public enum IfcConnectionTypeEnum { ATPATH, ATSTART, ATEND, NOTDEFINED };
	public enum IfcConstraintEnum { HARD, SOFT, ADVISORY, USERDEFINED, NOTDEFINED };
	public enum IfcControllerTypeEnum { FLOATING, PROPORTIONAL, PROPORTIONALINTEGRAL, PROPORTIONALINTEGRALDERIVATIVE, TIMEDTWOPOSITION, TWOPOSITION, USERDEFINED, NOTDEFINED };
	public enum IfcConstructionEquipmentResourceTypeEnum { DEMOLISHING, EARTHMOVING, ERECTING, HEATING, LIGHTING, PAVING, PUMPING, TRANSPORTING, USERDEFINED, NOTDEFINED };
	public enum IfcConstructionMaterialResourceTypeEnum { AGGREGATES, CONCRETE, DRYWALL, FUEL, GYPSUM, MASONRY, METAL, PLASTIC, WOOD, NOTDEFINED, USERDEFINED };
	public enum IfcConstructionProductResourceTypeEnum { ASSEMBLY, FORMWORK, NOTDEFINED, USERDEFINED };
	public enum IfcCooledBeamTypeEnum { ACTIVE, PASSIVE, USERDEFINED, NOTDEFINED };
	public enum IfcCoolingTowerTypeEnum { NATURALDRAFT, MECHANICALINDUCEDDRAFT, MECHANICALFORCEDDRAFT, USERDEFINED, NOTDEFINED };
	public enum IfcCostItemTypeEnum { USERDEFINED, NOTDEFINED };
	public enum IfcCostScheduleTypeEnum { BUDGET, COSTPLAN, ESTIMATE, TENDER, PRICEDBILLOFQUANTITIES, UNPRICEDBILLOFQUANTITIES, SCHEDULEOFRATES, USERDEFINED, NOTDEFINED };
	public enum IfcCoveringTypeEnum { CEILING, CLADDING, FLOORING, MOLDING, ROOFING, SKIRTINGBOARD, USERDEFINED, NOTDEFINED, INSULATION, MEMBRANE, SLEEVING, WRAPPING }; //IFC4 DELETED
	public enum IfcCrewResourceTypeEnum { OFFICE, SITE, NOTDEFINED, USERDEFINED };
	public enum IfcCurrencyEnum { AED, AES, ATS, AUD, BBD, BEG, BGL, BHD, BMD, BND, BRL, BSD, BWP, BZD, CAD, CBD, CHF, CLP, CNY, CYS, CZK, DDP, DEM, DKK, EGL, EST, EUR, FAK, FIM, FJD, FKP, FRF, GBP, GIP, GMD, GRX, HKD, HUF, ICK, IDR, ILS, INR, IRP, ITL, JMD, JOD, JPY, KES, KRW, KWD, KYD, LKR, LUF, MTL, MUR, MXN, MYR, NLG, NZD, OMR, PGK, PHP, PKR, PLN, PTN, QAR, RUR, SAR, SCR, SEK, SGD, SKP, THB, TRL, TTD, TWD, USD, VEB, VND, XEU, ZAR, ZWD, NOK, NOTDEFINED };
	public enum IfcCurtainWallTypeEnum { USERDEFINED, NOTDEFINED };
	public enum IfcCurveInterpolationEnum { LINEAR, LOG_LINEAR, LOG_LOG, NOTDEFINED }
	public enum IfcDamperTypeEnum { CONTROLDAMPER, FIREDAMPER, SMOKEDAMPER, FIRESMOKEDAMPER, BACKDRAFTDAMPER, RELIEFDAMPER, BLASTDAMPER, GRAVITYDAMPER, GRAVITYRELIEFDAMPER, BALANCINGDAMPER, FUMEHOODEXHAUST, USERDEFINED, NOTDEFINED };
	public enum IfcDataOriginEnum { MEASURED, PREDICTED, SIMULATED, USERDEFINED, NOTDEFINED };
	public enum IfcDerivedUnitEnum
	{
		ANGULARVELOCITYUNIT, COMPOUNDPLANEANGLEUNIT, DYNAMICVISCOSITYUNIT, HEATFLUXDENSITYUNIT,
		INTEGERCOUNTRATEUNIT, ISOTHERMALMOISTURECAPACITYUNIT, KINEMATICVISCOSITYUNIT, LINEARVELOCITYUNIT, MASSDENSITYUNIT,
		MASSFLOWRATEUNIT, MOISTUREDIFFUSIVITYUNIT, MOLECULARWEIGHTUNIT, SPECIFICHEATCAPACITYUNIT, THERMALADMITTANCEUNIT,
		THERMALCONDUCTANCEUNIT, THERMALRESISTANCEUNIT, THERMALTRANSMITTANCEUNIT, VAPORPERMEABILITYUNIT, VOLUMETRICFLOWRATEUNIT,
		ROTATIONALFREQUENCYUNIT, TORQUEUNIT, MOMENTOFINERTIAUNIT, LINEARMOMENTUNIT, LINEARFORCEUNIT, PLANARFORCEUNIT,
		MODULUSOFELASTICITYUNIT, SHEARMODULUSUNIT, LINEARSTIFFNESSUNIT, ROTATIONALSTIFFNESSUNIT, MODULUSOFSUBGRADEREACTIONUNIT,
		ACCELERATIONUNIT, CURVATUREUNIT, HEATINGVALUEUNIT, IONCONCENTRATIONUNIT, LUMINOUSINTENSITYDISTRIBUTIONUNIT, MASSPERLENGTHUNIT,
		MODULUSOFLINEARSUBGRADEREACTIONUNIT, MODULUSOFROTATIONALSUBGRADEREACTIONUNIT, PHUNIT, ROTATIONALMASSUNIT, SECTIONAREAINTEGRALUNIT,
		SECTIONMODULUSUNIT, SOUNDPOWERUNIT, SOUNDPRESSUREUNIT, TEMPERATUREGRADIENTUNIT, THERMALEXPANSIONCOEFFICIENTUNIT, WARPINGCONSTANTUNIT,
		WARPINGMOMENTUNIT, AREADENSITYUNIT, SOUNDPRESSURELEVELUNIT, TEMPERATURERATEOFCHANGEUNIT, USERDEFINED
	};
	public enum IfcDimensionExtentUsage { ORIGIN, TARGET };
	public enum IfcDirectionSenseEnum { POSITIVE, NEGATIVE };
	public enum IfcDiscreteAccessoryTypeEnum { ANCHORPLATE, BRACKET, SHOE, USERDEFINED, NOTDEFINED };
	public enum IfcDistributionChamberElementTypeEnum { FORMEDDUCT, INSPECTIONCHAMBER, INSPECTIONPIT, MANHOLE, METERCHAMBER, SUMP, TRENCH, VALVECHAMBER, USERDEFINED, NOTDEFINED };
	public enum IfcDistributionPortTypeEnum { CABLE, CABLECARRIER, DUCT, PIPE, USERDEFINED, NOTDEFINED }
	public enum IfcDistributionSystemEnum { AIRCONDITIONING, AUDIOVISUAL, CHEMICAL, CHILLEDWATER, COMMUNICATION, COMPRESSEDAIR, CONDENSERWATER,
		CONTROL, CONVEYING, DATA, DISPOSAL, DOMESTICCOLDWATER, DOMESTICHOTWATER, DRAINAGE, EARTHING, ELECTRICAL, ELECTROACOUSTIC, EXHAUST,
		FIREPROTECTION, FUEL, GAS, HAZARDOUS, HEATING, LIGHTING, LIGHTNINGPROTECTION, MUNICIPALSOLIDWASTE, OIL, OPERATIONAL, POWERGENERATION,
		RAINWATER, REFRIGERATION, SECURITY, SEWAGE, SIGNAL, STORMWATER, TELEPHONE, TV, VACUUM, VENT, VENTILATION, WASTEWATER, WATERSUPPLY, USERDEFINED, NOTDEFINED };
	public enum IfcDistributionSystemEnumPipe { CHEMICAL, CHILLEDWATER, COMPRESSEDAIR, CONDENSERWATER, CONVEYING, DISPOSAL, DOMESTICCOLDWATER,
		DOMESTICHOTWATER, DRAINAGE, FIREPROTECTION, FUEL, GAS, HAZARDOUS, HEATING, MUNICIPALSOLIDWASTE, OIL, OPERATIONAL, RAINWATER, 
		REFRIGERATION, SEWAGE, STORMWATER, VACUUM, VENT, WASTEWATER, WATERSUPPLY, USERDEFINED, NOTDEFINED };
	public enum IfcDistributionSystemEnumDuct { AIRCONDITIONING, EXHAUST, VENTILATION, USERDEFINED, NOTDEFINED };
	public enum IfcDistributionSystemEnumCable { AUDIOVISUAL, COMMUNICATION, CONTROL, DATA, EARTHING, ELECTRICAL, ELECTROACOUSTIC, LIGHTING, 
		LIGHTNINGPROTECTION, POWERGENERATION, SECURITY, SIGNAL, TELEPHONE, TV, USERDEFINED, NOTDEFINED };
	public enum IfcDistributionSystemEnumCableCarrier { AUDIOVISUAL, COMMUNICATION, CONTROL, DATA, EARTHING, ELECTRICAL, ELECTROACOUSTIC, 
		LIGHTING, LIGHTNINGPROTECTION, POWERGENERATION, SECURITY, SIGNAL, TELEPHONE, TV, USERDEFINED, NOTDEFINED };
	public enum IfcDocumentConfidentialityEnum { PUBLIC, RESTRICTED, CONFIDENTIAL, PERSONAL, USERDEFINED, NOTDEFINED };
	public enum IfcDocumentStatusEnum { DRAFT, FINALDRAFT, FINAL, REVISION, NOTDEFINED };
	public enum IfcDoorPanelOperationEnum { SWINGING, DOUBLE_ACTING, SLIDING, FOLDING, REVOLVING, ROLLINGUP, USERDEFINED, NOTDEFINED };
	public enum IfcDoorPanelPositionEnum { LEFT, MIDDLE, RIGHT, NOTDEFINED };
	public enum IfcDoorStyleConstructionEnum { ALUMINIUM, HIGH_GRADE_STEEL, STEEL, WOOD, ALUMINIUM_WOOD, ALUMINIUM_PLASTIC, PLASTIC, USERDEFINED, NOTDEFINED };
	public enum IfcDoorTypeOperationEnum { SINGLE_SWING_LEFT, SINGLE_SWING_RIGHT, DOUBLE_DOOR_SINGLE_SWING, DOUBLE_DOOR_SINGLE_SWING_OPPOSITE_LEFT, DOUBLE_DOOR_SINGLE_SWING_OPPOSITE_RIGHT, DOUBLE_SWING_LEFT, DOUBLE_SWING_RIGHT, DOUBLE_DOOR_DOUBLE_SWING, SLIDING_TO_LEFT, SLIDING_TO_RIGHT, DOUBLE_DOOR_SLIDING, FOLDING_TO_LEFT, FOLDING_TO_RIGHT, DOUBLE_DOOR_FOLDING, REVOLVING, ROLLINGUP, SWING_FIXED_LEFT, SWING_FIXED_RIGHT, USERDEFINED, NOTDEFINED };
	public enum IfcDoorTypeEnum { DOOR, GATE, TRAPDOOR, USERDEFINED, NOTDEFINED };
	public enum IfcDuctFittingTypeEnum { BEND, CONNECTOR, ENTRY, EXIT, JUNCTION, OBSTRUCTION, TRANSITION, USERDEFINED, NOTDEFINED };
	public enum IfcDuctSegmentTypeEnum { RIGIDSEGMENT, FLEXIBLESEGMENT, USERDEFINED, NOTDEFINED };
	public enum IfcDuctSilencerTypeEnum { FLATOVAL, RECTANGULAR, ROUND, USERDEFINED, NOTDEFINED };
	public enum IfcElectricApplianceTypeEnum { COMPUTER, DIRECTWATERHEATER, DISHWASHER, ELECTRICCOOKER, ELECTRICHEATER, FACSIMILE, FREESTANDINGFAN, FREEZER, FRIDGE_FREEZER, HANDDRYER, INDIRECTWATERHEATER, MICROWAVE, PHOTOCOPIER, PRINTER, REFRIGERATOR, RADIANTHEATER, SCANNER, TELEPHONE, TUMBLEDRYER, TV, VENDINGMACHINE, WASHINGMACHINE, WATERHEATER, WATERCOOLER, USERDEFINED, NOTDEFINED };
	public enum IfcElectricCurrentEnum { ALTERNATING, DIRECT, NOTDEFINED };
	public enum IfcElectricDistributionBoardTypeEnum { CONSUMERUNIT, DISTRIBUTIONBOARD, MOTORCONTROLCENTRE, SWITCHBOARD, USERDEFINED, NOTDEFINED };
	public enum IfcElectricDistributionPointFunctionEnum { ALARMPANEL, CONSUMERUNIT, CONTROLPANEL, DISTRIBUTIONBOARD, GASDETECTORPANEL, INDICATORPANEL, MIMICPANEL, MOTORCONTROLCENTRE, SWITCHBOARD, USERDEFINED, NOTDEFINED };
	public enum IfcElectricFlowStorageDeviceTypeEnum { BATTERY, CAPACITORBANK, HARMONICFILTER, INDUCTORBANK, UPS, USERDEFINED, NOTDEFINED };
	public enum IfcElectricGeneratorTypeEnum { USERDEFINED, NOTDEFINED };
	public enum IfcElectricHeaterTypeEnum { ELECTRICPOINTHEATER, ELECTRICCABLEHEATER, ELECTRICMATHEATER, USERDEFINED, NOTDEFINED };
	public enum IfcElectricMotorTypeEnum { DC, INDUCTION, POLYPHASE, RELUCTANCESYNCHRONOUS, SYNCHRONOUS, USERDEFINED, NOTDEFINED };
	public enum IfcElectricTimeControlTypeEnum { TIMECLOCK, TIMEDELAY, RELAY, USERDEFINED, NOTDEFINED };
	public enum IfcElementAssemblyTypeEnum { ACCESSORY_ASSEMBLY, ARCH, BEAM_GRID, BRACED_FRAME, GIRDER, REINFORCEMENT_UNIT, RIGID_FRAME, SLAB_FIELD, TRUSS, USERDEFINED, NOTDEFINED };
	public enum IfcElementCompositionEnum { COMPLEX, ELEMENT, PARTIAL, NA };
	public enum IfcEnergySequenceEnum { PRIMARY, SECONDARY, TERTIARY, AUXILIARY, USERDEFINED, NOTDEFINED };
	public enum IfcEngineTypeEnum { EXTERNALCOMBUSTION, INTERNALCOMBUSTION, USERDEFINED, NOTDEFINED };
	public enum IfcEnvironmentalImpactCategoryEnum { COMBINEDVALUE, DISPOSAL, EXTRACTION, INSTALLATION, MANUFACTURE, TRANSPORTATION, USERDEFINED, NOTDEFINED };
	public enum IfcEvaporativeCoolerTypeEnum { DIRECTEVAPORATIVERANDOMMEDIAAIRCOOLER, DIRECTEVAPORATIVERIGIDMEDIAAIRCOOLER, DIRECTEVAPORATIVESLINGERSPACKAGEDAIRCOOLER, DIRECTEVAPORATIVEPACKAGEDROTARYAIRCOOLER, DIRECTEVAPORATIVEAIRWASHER, INDIRECTEVAPORATIVEPACKAGEAIRCOOLER, INDIRECTEVAPORATIVEWETCOIL, INDIRECTEVAPORATIVECOOLINGTOWERORCOILCOOLER, INDIRECTDIRECTCOMBINATION, USERDEFINED, NOTDEFINED };
	public enum IfcEvaporatorTypeEnum { DIRECTEXPANSIONSHELLANDTUBE, DIRECTEXPANSIONTUBEINTUBE, DIRECTEXPANSIONBRAZEDPLATE, FLOODEDSHELLANDTUBE, SHELLANDCOIL, USERDEFINED, NOTDEFINED };
	public enum IfcEventTypeEnum { STARTEVENT, ENDEVENT, INTERMEDIATEEVENT, USERDEFINED, NOTDEFINED } //IFC4
	public enum IfcEventTriggerTypeEnum { EVENTRULE, EVENTMESSAGE, EVENTTIME, EVENTCOMPLEX, USERDEFINED, NOTDEFINED } //IFC4
	public enum IfcExternalSpatialElementTypeEnum { EXTERNAL, EXTERNAL_EARTH, EXTERNAL_WATER, EXTERNAL_FIRE, USERDEFINED, NOTDEFINED } //IFC4
	public enum IfcFanTypeEnum { CENTRIFUGALFORWARDCURVED, CENTRIFUGALRADIAL, CENTRIFUGALBACKWARDINCLINEDCURVED, CENTRIFUGALAIRFOIL, TUBEAXIAL, VANEAXIAL, PROPELLORAXIAL, USERDEFINED, NOTDEFINED };
	public enum IfcFastenerTypeEnum { GLUE, MORTAR, WELD, USERDEFINED, NOTDEFINED } //IFC4
	public enum IfcFilterTypeEnum { AIRPARTICLEFILTER, ODORFILTER, OILFILTER, STRAINER, WATERFILTER, USERDEFINED, NOTDEFINED };
	public enum IfcFireSuppressionTerminalTypeEnum { BREECHINGINLET, FIREHYDRANT, HOSEREEL, SPRINKLER, SPRINKLERDEFLECTOR, USERDEFINED, NOTDEFINED };
	public enum IfcFlowDirectionEnum { SOURCE, SINK, SOURCEANDSINK, NOTDEFINED };
	public enum IfcFlowInstrumentTypeEnum { PRESSUREGAUGE, THERMOMETER, AMMETER, FREQUENCYMETER, POWERFACTORMETER, PHASEANGLEMETER, VOLTMETER_PEAK, VOLTMETER_RMS, USERDEFINED, NOTDEFINED };
	public enum IfcFlowMeterTypeEnum { ENERGYMETER, GASMETER, OILMETER, WATERMETER, USERDEFINED, NOTDEFINED, ELECTRICMETER, FLOWMETER }; // IFC4 DELETED
	public enum IfcFootingTypeEnum { CAISSON_FOUNDATION, FOOTING_BEAM, PAD_FOOTING, PILE_CAP, STRIP_FOOTING, USERDEFINED, NOTDEFINED };
	public enum IfcFurnitureTypeEnum { CHAIR, TABLE, DESK, BED, FILECABINET, SHELF, SOFA, USERDEFINED, NOTDEFINED };
	public enum IfcGasTerminalTypeEnum { GASAPPLIANCE, GASBOOSTER, GASBURNER, USERDEFINED, NOTDEFINED };
	public enum IfcGeographicElementTypeEnum { TERRAIN, USERDEFINED, NOTDEFINED };
	public enum IfcGeometricProjectionEnum { GRAPH_VIEW, SKETCH_VIEW, MODEL_VIEW, PLAN_VIEW, REFLECTED_PLAN_VIEW, SECTION_VIEW, ELEVATION_VIEW, USERDEFINED, NOTDEFINED };
	public enum IfcGlobalOrLocalEnum { GLOBAL_COORDS, LOCAL_COORDS };
	public enum IfcGridTypeEnum { RECTANGULAR, RADIAL, TRIANGULAR, IRREGULAR, USERDEFINED, NOTDEFINED };
	public enum IfcHeatExchangerTypeEnum { PLATE, SHELLANDTUBE, USERDEFINED, NOTDEFINED };
	public enum IfcHumidifierTypeEnum { STEAMINJECTION, ADIABATICAIRWASHER, ADIABATICPAN, ADIABATICWETTEDELEMENT, ADIABATICATOMIZING, ADIABATICULTRASONIC, ADIABATICRIGIDMEDIA, ADIABATICCOMPRESSEDAIRNOZZLE, ASSISTEDELECTRIC, ASSISTEDNATURALGAS, ASSISTEDPROPANE, ASSISTEDBUTANE, ASSISTEDSTEAM, USERDEFINED, NOTDEFINED };
	public enum IfcInternalOrExternalEnum { INTERNAL, EXTERNAL, EXTERNAL_EARTH, EXTERNAL_WATER, EXTERNAL_FIRE, NOTDEFINED };
	public enum IfcInventoryTypeEnum { ASSETINVENTORY, SPACEINVENTORY, FURNITUREINVENTORY, USERDEFINED, NOTDEFINED };
	public enum IfcInterceptorTypeEnum { CYCLONIC, GREASE, OIL, PETROL, USERDEFINED, NOTDEFINED };
	public enum IfcJunctionBoxTypeEnum { USERDEFINED, NOTDEFINED };
	public enum IfcKnotType { UNIFORM_KNOTS, QUASI_UNIFORM_KNOTS, PIECEWISE_BEZIER_KNOTS, UNSPECIFIED };
	public enum IfcLaborResourceTypeEnum { ADMINISTRATION ,CARPENTRY ,CLEANING ,CONCRETE ,DRYWALL ,ELECTRIC ,FINISHING ,FLOORING ,GENERAL ,HVAC ,LANDSCAPING ,MASONRY ,PAINTING ,PAVING ,PLUMBING ,ROOFING ,SITEGRADING ,STEELWORK ,SURVEYING ,USERDEFINED ,NOTDEFINED};
	public enum IfcLampTypeEnum { COMPACTFLUORESCENT, FLUORESCENT, HIGHPRESSUREMERCURY, HIGHPRESSURESODIUM, METALHALIDE, TUNGSTENFILAMENT, USERDEFINED, NOTDEFINED };
	public enum IfcLayerSetDirectionEnum { AXIS1, AXIS2, AXIS3 };
	public enum IfcLightDistributionCurveEnum { TYPE_A, TYPE_B, TYPE_C, NOTDEFINED };
	public enum IfcLightEmissionSourceEnum { COMPACTFLUORESCENT, FLUORESCENT, HIGHPRESSUREMERCURY, HIGHPRESSURESODIUM, LIGHTEMITTINGDIODE, LOWPRESSURESODIUM, LOWVOLTAGEHALOGEN, MAINVOLTAGEHALOGEN, METALHALIDE, TUNGSTENFILAMENT, NOTDEFINED };
	public enum IfcLightFixtureTypeEnum { POINTSOURCE, DIRECTIONSOURCE, USERDEFINED, NOTDEFINED };
	public enum IfcLoadGroupTypeEnum { LOAD_GROUP, LOAD_CASE, LOAD_COMBINATION, USERDEFINED, NOTDEFINED, LOAD_COMBINATION_GROUP }; //IFC4 DELETED 
	public enum IfcLogicalEnum { TRUE, FALSE, UNKNOWN };
	public enum IfcLogicalOperatorEnum { LOGICALAND, LOGICALOR, LOGICALXOR, LOGICALNOTAND, LOGICALNOTOR, NONE };
	public enum IfcMechanicalFastenerTypeEnum { ANCHORBOLT, BOLT, DOWEL, NAIL, NAILPLATE, RIVET, SCREW, SHEARCONNECTOR, STAPLE, STUDSHEARCONNECTOR, USERDEFINED, NOTDEFINED }
	public enum IfcMedicalDeviceTypeEnum { AIRSTATION, FEEDAIRUNIT, OXYGENGENERATOR, OXYGENPLANT, VACUUMSTATION, USERDEFINED, NOTDEFINED };
	public enum IfcMemberTypeEnum { BRACE, CHORD, COLLAR, MEMBER, MULLION, PLATE, POST, PURLIN, RAFTER, STRINGER, STRUT, STUD, USERDEFINED, NOTDEFINED };
	public enum IfcMotorConnectionTypeEnum { BELTDRIVE, COUPLING, DIRECTDRIVE, USERDEFINED, NOTDEFINED };
	public enum IfcNullStyle { NULL }; //DEPRECEATED
	public enum IfcObjectiveEnum { CODECOMPLIANCE, CODEWAIVER, DESIGNINTENT, EXTERNAL, HEALTHANDSAFETY, MERGECONFLICT, MODELVIEW, PARAMETER, REQUIREMENT, SPECIFICATION, TRIGGERCONDITION, USERDEFINED, NOTDEFINED };
	public enum IfcObjectTypeEnum { PRODUCT, PROCESS, CONTROL, RESOURCE, ACTOR, GROUP, PROJECT, NOTDEFINED };
	public enum IfcOccupantTypeEnum { ASSIGNEE, ASSIGNOR, LESSEE, LESSOR, LETTINGAGENT, OWNER, TENANT, USERDEFINED, NOTDEFINED };
	public enum IfcOpeningElementTypeEnum { OPENING, RECESS, USERDEFINED, NOTDEFINED }
	public enum IfcOutletTypeEnum { AUDIOVISUALOUTLET, COMMUNICATIONSOUTLET, POWEROUTLET, USERDEFINED, NOTDEFINED };
	public enum IfcPermeableCoveringOperationEnum { GRILL, LOUVER, SCREEN, USERDEFINED, NOTDEFINED };
	public enum IfcPhysicalOrVirtualEnum { PHYSICAL, VIRTUAL, NOTDEFINED };
	public enum IfcPileConstructionEnum { BORED, CAST_IN_PLACE, COMPOSITE, DRIVEN, JETGROUTING, PRECAST_CONCRETE, PREFAB_STEEL, USERDEFINED, NOTDEFINED };
	public enum IfcPileTypeEnum { COHESION, FRICTION, SUPPORT, USERDEFINED, NOTDEFINED };
	public enum IfcPipeFittingTypeEnum { BEND, CONNECTOR, ENTRY, EXIT, JUNCTION, OBSTRUCTION, TRANSITION, USERDEFINED, NOTDEFINED };
	public enum IfcPipeSegmentTypeEnum { FLEXIBLESEGMENT, RIGIDSEGMENT, GUTTER, SPOOL, USERDEFINED, NOTDEFINED };
	public enum IfcPlateTypeEnum { CURTAIN_PANEL, SHEET, USERDEFINED, NOTDEFINED };
	public enum IfcPreferredSurfaceCurveRepresentation { CURVE3D, PCURVE_S1, PCURVE_S2 };
	public enum IfcProcedureTypeEnum { ADVICE_CAUTION, ADVICE_NOTE, ADVICE_WARNING, CALIBRATION, DIAGNOSTIC, SHUTDOWN, STARTUP, USERDEFINED, NOTDEFINED };
	public enum IfcProfileTypeEnum { CURVE, AREA };
	public enum IfcProjectedOrTrueLengthEnum { PROJECTED_LENGTH, TRUE_LENGTH };
	public enum IfcProjectOrderRecordTypeEnum { CHANGE, MAINTENANCE, MOVE, PURCHASE, WORK, USERDEFINED, NOTDEFINED };
	public enum IfcProjectOrderTypeEnum { CHANGEORDER, MAINTENANCEWORKORDER, MOVEORDER, PURCHASEORDER, WORKORDER, USERDEFINED, NOTDEFINED };
	public enum IfcProjectionElementTypeEnum { USERDEFINED, NOTDEFINED }
	public enum IfcPropertySetTemplateTypeEnum { PSET_TYPEDRIVENONLY, PSET_TYPEDRIVENOVERRIDE, PSET_OCCURRENCEDRIVEN, PSET_PERFORMANCEDRIVEN, QTO_TYPEDRIVENONLY, QTO_TYPEDRIVENOVERRIDE, QTO_OCCURRENCEDRIVEN, NOTDEFINED };
	public enum IfcPropertySourceEnum { DESIGN, DESIGNMAXIMUM, DESIGNMINIMUM, SIMULATED, ASBUILT, COMMISSIONING, MEASURED, USERDEFINED, NOTKNOWN };
	public enum IfcProtectiveDeviceTrippingUnitTypeEnum { ELECTRONIC, ELECTROMAGNETIC, RESIDUALCURRENT, THERMAL, USERDEFINED, NOTDEFINED };
	public enum IfcProtectiveDeviceTypeEnum { FUSEDISCONNECTOR, CIRCUITBREAKER, EARTHFAILUREDEVICE, RESIDUALCURRENTCIRCUITBREAKER, RESIDUALCURRENTSWITCH, VARISTOR, USERDEFINED, NOTDEFINED };
	public enum IfcPumpTypeEnum { CIRCULATOR, ENDSUCTION, SPLITCASE, VERTICALINLINE, VERTICALTURBINE, USERDEFINED, NOTDEFINED };
	public enum IfcRailingTypeEnum { HANDRAIL, GUARDRAIL, BALUSTRADE, USERDEFINED, NOTDEFINED };
	public enum IfcRampFlightTypeEnum { STRAIGHT, SPIRAL, USERDEFINED, NOTDEFINED };
	public enum IfcRampTypeEnum { STRAIGHT_RUN_RAMP, TWO_STRAIGHT_RUN_RAMP, QUARTER_TURN_RAMP, TWO_QUARTER_TURN_RAMP, HALF_TURN_RAMP, SPIRAL_RAMP, USERDEFINED, NOTDEFINED };
	public enum IfcRecurrenceTypeEnum { DAILY, WEEKLY, MONTHLY_BY_DAY_OF_MONTH, MONTHLY_BY_POSITION, BY_DAY_COUNT, BY_WEEKDAY_COUNT, YEARLY_BY_DAY_OF_MONTH, YEARLY_BY_POSITION };
	public enum IfcReflectanceMethodEnum { BLINN, FLAT, GLASS, MATT, METAL, MIRROR, PHONG, PLASTIC, STRAUSS, NOTDEFINED };
	public enum IfcReinforcingBarSurfaceEnum { PLAIN, TEXTURED, NOTDEFINED };
	public enum IfcReinforcingBarRoleEnum { MAIN, SHEAR, LIGATURE, STUD, PUNCHING, EDGE, RING, ANCHORING, USERDEFINED, NOTDEFINED };
	public enum IfcReinforcingBarTypeEnum { MAIN, SHEAR, LIGATURE, STUD, PUNCHING, EDGE, RING, ANCHORING, USERDEFINED, NOTDEFINED };
	public enum IfcReinforcingMeshTypeEnum { USERDEFINED, NOTDEFINED };
	public enum IfcResourceConsumptionEnum { CONSUMED, PARTIALLYCONSUMED, NOTCONSUMED, OCCUPIED, PARTIALLYOCCUPIED, NOTOCCUPIED, USERDEFINED, NOTDEFINED };
	public enum IfcRibPlateDirectionEnum { DIRECTION_X, DIRECTION_Y };
	public enum IfcRoleEnum { SUPPLIER, MANUFACTURER, CONTRACTOR, SUBCONTRACTOR, ARCHITECT, STRUCTURALENGINEER, COSTENGINEER, CLIENT, BUILDINGOWNER, BUILDINGOPERATOR, MECHANICALENGINEER, ELECTRICALENGINEER, PROJECTMANAGER, FACILITIESMANAGER, CIVILENGINEER, COMMISSIONINGENGINEER, ENGINEER, OWNER, CONSULTANT, CONSTRUCTIONMANAGER, FIELDCONSTRUCTIONMANAGER, RESELLER, USERDEFINED, NOTDEFINED };
	public enum IfcRoofTypeEnum { FLAT_ROOF, SHED_ROOF, GABLE_ROOF, HIP_ROOF, HIPPED_GABLE_ROOF, GAMBREL_ROOF, MANSARD_ROOF, BARREL_ROOF, RAINBOW_ROOF, BUTTERFLY_ROOF, PAVILION_ROOF, DOME_ROOF, FREEFORM, NOTDEFINED, USERDEFINED };
	public enum IfcSanitaryTerminalTypeEnum { BATH, BIDET, CISTERN, SHOWER, SINK, SANITARYFOUNTAIN, TOILETPAN, URINAL, WASHHANDBASIN, WCSEAT, USERDEFINED, NOTDEFINED };
	public enum IfcSectionTypeEnum { UNIFORM, TAPERED };
	public enum IfcSensorTypeEnum { COSENSOR, CO2SENSOR, FIRESENSOR, FLOWSENSOR, GASSENSOR, HEATSENSOR, HUMIDITYSENSOR, LIGHTSENSOR, MOISTURESENSOR, MOVEMENTSENSOR, PRESSURESENSOR, SMOKESENSOR, SOUNDSENSOR, TEMPERATURESENSOR, USERDEFINED, NOTDEFINED };
	public enum IfcSequenceEnum { START_START, START_FINISH, FINISH_START, FINISH_FINISH, USERDEFINED, NOTDEFINED };
	public enum IfcServiceLifeTypeEnum { ACTUALSERVICELIFE, EXPECTEDSERVICELIFE, OPTIMISTICREFERENCESERVICELIFE, PESSIMISTICREFERENCESERVICELIFE, REFERENCESERVICELIFE };
	public enum IfcServiceLifeFactorTypeEnum { A_QUALITYOFCOMPONENTS, B_DESIGNLEVEL, C_WORKEXECUTIONLEVEL, D_INDOORENVIRONMENT, E_OUTDOORENVIRONMENT, F_INUSECONDITIONS, G_MAINTENANCELEVEL, USERDEFINED, NOTDEFINED };
	public enum IfcShadingDeviceTypeEnum { JALOUSIE, SHUTTER, AWNING, USERDEFINED, NOTDEFINED };
	public enum IfcSimplePropertyTemplateTypeEnum { P_SINGLEVALUE, P_ENUMERATEDVALUE, P_BOUNDEDVALUE, P_LISTVALUE, P_TABLEVALUE, P_REFERENCEVALUE, Q_LENGTH, Q_AREA, Q_VOLUME, Q_COUNT, Q_WEIGHT, Q_TIME, NOTDEFINED };
	public enum IfcSIPrefix { EXA, PETA, TERA, GIGA, MEGA, KILO, HECTO, DECA, DECI, CENTI, MILLI, MICRO, NANO, PICO, FEMTO, ATTO, NONE };
	public enum IfcSIUnitName { AMPERE, BECQUEREL, CANDELA, COULOMB, CUBIC_METRE, DEGREE_CELSIUS, FARAD, GRAM, GRAY, HENRY, HERTZ, JOULE, KELVIN, LUMEN, LUX, METRE, MOLE, NEWTON, OHM, PASCAL, RADIAN, SECOND, SIEMENS, SIEVERT, SQUARE_METRE, STERADIAN, TESLA, VOLT, WATT, WEBER };
	public enum IfcSlabTypeEnum { FLOOR, ROOF, LANDING, BASESLAB, USERDEFINED, NOTDEFINED };
	public enum IfcSolarDeviceTypeEnum { SOLARCOLLECTOR, SOLARPANEL, USERDEFINED, NOTDEFINED };
	public enum IfcSoundScaleEnum { DBA, DBB, DBC, NC, NR, USERDEFINED, NOTDEFINED };
	public enum IfcSpaceHeaterTypeEnum { SECTIONALRADIATOR, PANELRADIATOR, TUBULARRADIATOR, CONVECTOR, BASEBOARDHEATER, FINNEDTUBEUNIT, UNITHEATER, USERDEFINED, NOTDEFINED };
	public enum IfcSpaceTypeEnum { SPACE, PARKING, GFA, INTERNAL, EXTERNAL, USERDEFINED, NOTDEFINED };
	public enum IfcSpatialZoneTypeEnum { CONSTRUCTION, FIRESAFETY, LIGHTING, OCCUPANCY, SECURITY, THERMAL, VENTILATION, USERDEFINED, NOTDEFINED };
	public enum IfcStairTypeEnum { STRAIGHT_RUN_STAIR, TWO_STRAIGHT_RUN_STAIR, QUARTER_WINDING_STAIR, QUARTER_TURN_STAIR, HALF_WINDING_STAIR, HALF_TURN_STAIR, TWO_QUARTER_WINDING_STAIR, TWO_QUARTER_TURN_STAIR, THREE_QUARTER_WINDING_STAIR, THREE_QUARTER_TURN_STAIR, SPIRAL_STAIR, DOUBLE_RETURN_STAIR, CURVED_RUN_STAIR, TWO_CURVED_RUN_STAIR, USERDEFINED, NOTDEFINED };
	public enum IfcStackTerminalTypeEnum { BIRDCAGE, COWL, RAINWATERHOPPER, USERDEFINED, NOTDEFINED };
	public enum IfcStairFlightTypeEnum { STRAIGHT, WINDER, SPIRAL, CURVED, FREEFORM, USERDEFINED, NOTDEFINED };
	public enum IfcStateEnum { READWRITE, READONLY, LOCKED, READWRITELOCKED, READONLYLOCKED, NOTDEFINED };
	public enum IfcStatusEnum { NEW, EXISTING, DEMOLISH, TEMPORARY, OTHER, NOTKNOWN, UNSET };
	public enum IfcStructuralCurveActivityTypeEnum {CONST, LINEAR, POLYGONAL, EQUIDISTANT, SINUS, PARABOLA,  DISCRETE, USERDEFINED,  NOTDEFINED}
	public enum IfcStructuralCurveMemberTypeEnum { RIGID_JOINED_MEMBER, PIN_JOINED_MEMBER, CABLE, TENSION_MEMBER, COMPRESSION_MEMBER, USERDEFINED, NOTDEFINED };
	public enum IfcStructuralSurfaceActivityTypeEnum {CONST, BILINEAR, DISCRETE, ISOCONTOUR, USERDEFINED,  NOTDEFINED}
	public enum IfcStructuralSurfaceMemberTypeEnum { BENDING_ELEMENT, MEMBRANE_ELEMENT, SHELL, USERDEFINED, NOTDEFINED };
	public enum IfcSubContractResourceTypeEnum { PURCHASE, WORK, USERDEFINED, NOTDEFINED };
	public enum IfcSurfaceSide { POSITIVE, NEGATIVE, BOTH };
	public enum IfcSurfaceTextureEnum { BUMP, OPACITY, REFLECTION, SELFILLUMINATION, SHININESS, SPECULAR, TEXTURE, TRANSPARENCYMAP, NOTDEFINED };
	public enum IfcSwitchingDeviceTypeEnum { CONTACTOR, EMERGENCYSTOP, STARTER, SWITCHDISCONNECTOR, TOGGLESWITCH, USERDEFINED, NOTDEFINED };
	public enum IfcSystemFurnitureElementTypeEnum { PANEL, WORKSURFACE, USERDEFINED, NOTDEFINED };
	public enum IfcTankTypeEnum { EXPANSION, PRESSUREVESSEL, USERDEFINED, NOTDEFINED, PREFORMED, SECTIONAL, }; //IFC4 DELETED
	public enum IfcTaskTypeEnum { ATTENDANCE, CONSTRUCTION, DEMOLITION, DISMANTLE, DISPOSAL, INSTALLATION, LOGISTIC, MAINTENANCE, MOVE, OPERATION, REMOVAL, RENOVATION, USERDEFINED, NOTDEFINED }; //IFC4
	public enum IfcTaskDurationEnum { ELAPSEDTIME, WORKTIME, NOTDEFINED };
	public enum IfcTendonTypeEnum { STRAND, WIRE, BAR, COATED, USERDEFINED, NOTDEFINED };
	public enum IfcTendonAnchorTypeEnum { COUPLER, FIXED_END, TENSIONING_END, USERDEFINED, NOTDEFINED };
	public enum IfcTextPath { LEFT, RIGHT, UP, DOWN };
	public enum IfcThermalLoadSourceEnum { PEOPLE, LIGHTING, EQUIPMENT, VENTILATIONINDOORAIR, VENTILATIONOUTSIDEAIR, RECIRCULATEDAIR, EXHAUSTAIR, AIREXCHANGERATE, DRYBULBTEMPERATURE, RELATIVEHUMIDITY, INFILTRATION, USERDEFINED, NOTDEFINED };
	public enum IfcThermalLoadTypeEnum { SENSIBLE, LATENT, RADIANT, NOTDEFINED };
	public enum IfcTimeSeriesDataTypeEnum { CONTINUOUS, DISCRETE, DISCRETEBINARY, PIECEWISEBINARY, PIECEWISECONSTANT, PIECEWISECONTINUOUS, NOTDEFINED };
	public enum IfcTimeSeriesScheduleTypeEnum { ANNUAL, MONTHLY, WEEKLY, DAILY, USERDEFINED, NOTDEFINED };
	public enum IfcTransformerTypeEnum { CURRENT, FREQUENCY, VOLTAGE, USERDEFINED, NOTDEFINED };
	public enum IfcTransitionCode { DISCONTINUOUS, CONTINUOUS, CONTSAMEGRADIENT, CONTSAMEGRADIENTSAMECURVATURE };
	public enum IfcTransitionCurveType { BIQUADRATICPARABOLA, BLOSSCURVE, CLOTHOIDCURVE, COSINECURVE, CUBICPARABOLA, SINECURVE };
	public enum IfcTransportElementTypeEnum { ELEVATOR, ESCALATOR, MOVINGWALKWAY, USERDEFINED, NOTDEFINED };
	public enum IfcTrimmingPreference { CARTESIAN, PARAMETER, UNSPECIFIED };
	public enum IfcTubeBundleTypeEnum { FINNED, USERDEFINED, NOTDEFINED };
	public enum IfcUnitaryControlElementTypeEnum { 	ALARMPANEL, CONTROLPANEL, GASDETECTIONPANEL, INDICATORPANEL, MIMICPANEL, HUMIDISTAT, THERMOSTAT, WEATHERSTATION, USERDEFINED, NOTDEFINED };
	public enum IfcUnitaryEquipmentTypeEnum { AIRHANDLER, AIRCONDITIONINGUNIT, SPLITSYSTEM, ROOFTOPUNIT, USERDEFINED, NOTDEFINED };
	public enum IfcUnitEnum { ABSORBEDDOSEUNIT, AMOUNTOFSUBSTANCEUNIT, AREAUNIT, DOSEEQUIVALENTUNIT, ELECTRICCAPACITANCEUNIT, ELECTRICCHARGEUNIT, ELECTRICCONDUCTANCEUNIT, ELECTRICCURRENTUNIT, ELECTRICRESISTANCEUNIT, ELECTRICVOLTAGEUNIT, ENERGYUNIT, FORCEUNIT, FREQUENCYUNIT, ILLUMINANCEUNIT, INDUCTANCEUNIT, LENGTHUNIT, LUMINOUSFLUXUNIT, LUMINOUSINTENSITYUNIT, MAGNETICFLUXDENSITYUNIT, MAGNETICFLUXUNIT, MASSUNIT, PLANEANGLEUNIT, POWERUNIT, PRESSUREUNIT, RADIOACTIVITYUNIT, SOLIDANGLEUNIT, THERMODYNAMICTEMPERATUREUNIT, TIMEUNIT, VOLUMEUNIT, USERDEFINED };
	public enum IfcValveTypeEnum { AIRRELEASE, ANTIVACUUM, CHANGEOVER, CHECK, COMMISSIONING, DIVERTING, DRAWOFFCOCK, DOUBLECHECK, DOUBLEREGULATING, FAUCET, FLUSHING, GASCOCK, GASTAP, ISOLATING, MIXING, PRESSUREREDUCING, PRESSURERELIEF, REGULATING, SAFETYCUTOFF, STEAMTRAP, STOPCOCK, USERDEFINED, NOTDEFINED };
	public enum IfcVibrationIsolatorTypeEnum { COMPRESSION, SPRING, USERDEFINED, NOTDEFINED };
	public enum IfcVoidingFeatureTypeEnum { CUTOUT, NOTCH, HOLE, MITER, CHAMFER, EDGE, USERDEFINED, NOTDEFINED };
	public enum IfcWallTypeEnum { STANDARD, ELEMENTEDWALL,  MOVABLE, PARAPET, PARTITIONING, PLUMBINGWALL, POLYGONAL, SHEAR, SOLIDWALL, USERDEFINED, NOTDEFINED }; //IFC4 change STANDARD, POLYGONAL, ELEMENTEDWALL
	public enum IfcWasteTerminalTypeEnum { FLOORTRAP, FLOORWASTE, GULLYSUMP, GULLYTRAP, GREASEINTERCEPTOR, OILINTERCEPTOR, PETROLINTERCEPTOR, ROOFDRAIN, WASTEDISPOSALUNIT, WASTETRAP, USERDEFINED, NOTDEFINED }; // IFC4  
	public enum IfcWindowPanelOperationEnum { SIDEHUNGRIGHTHAND, SIDEHUNGLEFTHAND, TILTANDTURNRIGHTHAND, TILTANDTURNLEFTHAND, TOPHUNG, BOTTOMHUNG, PIVOTHORIZONTAL, PIVOTVERTICAL, SLIDINGHORIZONTAL, SLIDINGVERTICAL, REMOVABLECASEMENT, FIXEDCASEMENT, OTHEROPERATION, NOTDEFINED };
	public enum IfcWindowPanelPositionEnum { LEFT, MIDDLE, RIGHT, BOTTOM, TOP, NOTDEFINED };
	public enum IfcWindowStyleConstructionEnum { ALUMINIUM, HIGH_GRADE_STEEL, STEEL, WOOD, ALUMINIUM_WOOD, PLASTIC, OTHER_CONSTRUCTION, NOTDEFINED };
	public enum IfcWindowStyleOperationEnum { SINGLE_PANEL, DOUBLE_PANEL_VERTICAL, DOUBLE_PANEL_HORIZONTAL, TRIPLE_PANEL_VERTICAL, TRIPLE_PANEL_BOTTOM, TRIPLE_PANEL_TOP, TRIPLE_PANEL_LEFT, TRIPLE_PANEL_RIGHT, TRIPLE_PANEL_HORIZONTAL, USERDEFINED, NOTDEFINED };
	public enum IfcWindowTypeEnum { WINDOW, SKYLIGHT, LIGHTDOME, USERDEFINED, NOTDEFINED };
	public enum IfcWindowTypePartitioningEnum { SINGLE_PANEL, DOUBLE_PANEL_VERTICAL, DOUBLE_PANEL_HORIZONTAL, TRIPLE_PANEL_VERTICAL, TRIPLE_PANEL_BOTTOM, TRIPLE_PANEL_TOP, TRIPLE_PANEL_LEFT, TRIPLE_PANEL_RIGHT, TRIPLE_PANEL_HORIZONTAL, USERDEFINED, NOTDEFINED };
	public enum IfcWorkCalendarTypeEnum { FIRSTSHIFT, SECONDSHIFT, THIRDSHIFT, USERDEFINED, NOTDEFINED };
	public enum IfcWorkControlTypeEnum { ACTUAL, BASELINE, PLANNED, USERDEFINED, NOTDEFINED };
	public enum IfcWorkPlanTypeEnum { ACTUAL, BASELINE, PLANNED, USERDEFINED, NOTDEFINED };
	public enum IfcWorkScheduleTypeEnum { ACTUAL, BASELINE, PLANNED, USERDEFINED, NOTDEFINED };

	public enum PEnum_AcquisitionMethod { GPS, LASERSCAN_AIRBORNE, LASERSCAN_GROUND, SONAR, THEODOLITE, USERDEFINED, NOTKNOWN, UNSET };
	public enum PEnum_ActionRequestChance { HAS_OCCURRED, HIGH, MODERATE, LOW, UNKNOWN };
	public enum PEnum_ActionRequestImpact { VERY_HIGH, HIGH, MODERATE, LOW, UNKNOWN };
	public enum PEnum_ActionRequestRisk { VERY_HIGH, HIGH, MODERATE, LOW, UNKNOWN };
	public enum PEnum_ActionRequestType { CHANGE, CLAIM, COORDINATION, ENVIRONMENTAL, FUNCTION, INDOORAIRQUALITY, INSTALLATION, RFI, SAFETY, SPECIFICATION };
	public enum PEnum_ActuatorApplication { ENTRYEXITDEVICE, FIRESMOKEDAMPERACTUATOR, DAMPERACTUATOR, VALVEPOSITIONER, LAMPACTUATOR, SUNBLINDACTUATOR, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AirHandlerConstruction { MANUFACTUREDITEM, CONSTRUCTEDONSITE, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AirHandlerFanCoilArrangement { BLOWTHROUGH, DRAWTHROUGH, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AirSideSystemDistributionType { SINGLEDUCT, DUALDUCT, MULTIZONE, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AirSideSystemType { CONSTANTVOLUME, CONSTANTVOLUMESINGLEZONE, CONSTANTVOLUMEMULTIPLEZONEREHEAT, CONSTANTVOLUMEBYPASS, VARIABLEAIRVOLUME, VARIABLEAIRVOLUMEREHEAT, VARIABLEAIRVOLUMEINDUCTION, VARIABLEAIRVOLUMEFANPOWERED, VARIABLEAIRVOLUMEDUALCONDUIT, VARIABLEAIRVOLUMEVARIABLEDIFFUSERS, VARIABLEAIRVOLUMEVARIABLETEMPERATURE, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AirTerminalAirflowType { SUPPLYAIR, RETURNAIR, EXHAUSTAIR, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AirTerminalBoxArrangementType { SINGLEDUCT, DUALDUCT, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AirTerminalBoxReheatType { ELECTRICALREHEAT, WATERCOILREHEAT, STEAMCOILREHEAT, GASREHEAT, NONE, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AirTerminalCoreType { SHUTTERBLADE, CURVEDBLADE, REMOVABLE, REVERSIBLE, NONE, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AirTerminalDischargeDirection { PARALLEL, PERPENDICULAR, ADJUSTABLE, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AirTerminalFaceType { FOURWAYPATTERN, SINGLEDEFLECTION, DOUBLEDEFLECTION, SIGHTPROOF, EGGCRATE, PERFORATED, LOUVERED, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AirTerminalFinishType { ANNODIZED, PAINTED, NONE, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AirTerminalFlowControlType { DAMPER, BELLOWS, NONE, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AirTerminalFlowPattern { LINEARSINGLE, LINEARDOUBLE, LINEARFOURWAY, RADIAL, SWIRL, DISPLACMENT, COMPACTJET, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AirTerminalLocation { SIDEWALLHIGH, SIDEWALLLOW, CEILINGPERIMETER, CEILINGINTERIOR, FLOOR, SILL, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AirTerminalMountingType { SURFACE, FLATFLUSH, LAYIN, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AirTerminalShape { ROUND, RECTANGULAR, SQUARE, SLOT, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AssemblyPlace { FACTORY, OFFSITE, SITE, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AssetAccountingType { FIXED, NONFIXED, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AssetInsuranceType { PERSONAL, REAL, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AssetTaxType { CAPITALISED, EXPENSED, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AssetType { FIXED, MOVEABLE };
	public enum PEnum_AudioVisualAmplifierType { FIXED, VARIABLE, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AudioVisualCameraType { PHOTO, VIDEO, AUDIOVIDEO, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AudioVisualDisplayTouchScreen { SINGLETOUCH, MULTITOUCH, NONE, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AudioVisualDisplayType { CRT, DLP, LCD, LED, PLASMA, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AudioVisualPlayerType { AUDIO, VIDEO, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AudioVisualProjectorType { OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AudioVisualReceiverType { AUDIO, AUDIOVIDEO, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AudioVisualSpeakerMounting { FREESTANDING, CEILING, WALL, OUTDOOR, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AudioVisualSpeakerType { FULLRANGE, MIDRANGE, WOOFER, TWEETER, COAXIAL, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_AudioVisualTunerType { AUDIO, VIDEO, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_BoilerOperatingMode { FIXED, TWOSTEP, MODULATING, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_ConstructionProductResourceCategory { LABOR, MATERIAL, TOOLS, TRAINING };
	public enum PEnum_ConstructionProductResourceTypeCategory { PART, PARTSET, LUBRICANT, OTHER, SPARE, SPARESET };
	public enum PEnum_ConductorFunctionEnum { PHASE_L1, PHASE_L2, PHASE_L3, NEUTRAL, PROTECTIVEEARTH, PROTECTIVEEARTHNEUTRAL, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_DuctConnectionType { BEADEDSLEEVE, COMPRESSION, CRIMP, DRAWBAND, DRIVESLIP, FLANGED, OUTSIDESLEEVE, SLIPON, SOLDERED, SSLIP, STANDINGSEAM, SWEDGE, WELDED, OTHER, NONE, USERDEFINED, NOTDEFINED }
	public enum PEnum_DistributionPortElectricalType { ACPLUG, DCPLUG, COAXIAL, CRIMP, RJ, RADIO, DIN, DSUB, DVI, EIAJ, HDMI, RCA, SOCKET, TRS, USB, XLR, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_DistributionPortGender { MALE, FEMALE, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_ElectricActuatorType { MOTORDRIVE, MAGNETIC, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_Status { NEW, EXISTING, DEMOLISH, TEMPORARY, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_ElementComponentDeliveryType { CAST_IN_PLACE, WELDED_TO_STRUCTURE, LOOSE, ATTACHED_FOR_DELIVERY, PRECAST, NOTDEFINED };
	public enum PEnum_ElementComponentCorrosionTreatment { PAINTED, EPOXYCOATED, GALVANISED, STAINLESS, NONE, NOTDEFINED };
	public enum PEnum_EnergySource { COAL, COAL_PULVERIZED, ELECTRICITY, GAS, OIL, PROPANE, WOOD, WOOD_CHIP, WOOD_PELLET, WOOD_PULVERIZED, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_FailPosition { FAILOPEN, FAILCLOSED, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_HeatTransferType { SENSIBLE, LATENT, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_LifeCyclePhase { ACQUISITION, CRADLETOSITE, DECONSTRUCTION, DISPOSAL, DISPOSALTRANSPORT, GROWTH, INSTALLATION, MAINTENANCE, MANUFACTURE, OCCUPANCY, OPERATION, PROCUREMENT, PRODUCTION, PRODUCTIONTRANSPORT, RECOVERY, REFURBISHMENT, REPAIR, REPLACEMENT, TRANSPORT, USAGE, WASTE, WHOLELIFECYCLE, USERDEFINED, NOTDEFINED };
	public enum PEnum_LightFixtureMountingType { CABLESPANNED, FREESTANDING, POLE_SIDE, POLE_TOP, RECESSED, SURFACE, SUSPENDED, TRACKMOUNTED, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_LightFixturePlacingType { CEILING, FLOOR, FURNITURE, POLE, WALL, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_PipeEndStyleTreatment { BRAZED, COMPRESSION, GROOVED, OUTSIDESLEEVE, SOLDERED, SWEDGE, THREADED, WELDED, OTHER, NONE, USERDEFINED, NOTDEFINED }
	public enum PEnum_PipeFittingJunctionType { TEE, CROSS, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_PropertyAgreementType { ASSIGNMENT, LEASE, TENANT, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_PumpBaseType { FRAME, BASE, NONE, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_PumpDriveConnectionType { DIRECTDRIVE, BELTDRIVE, COUPLING, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_ReinforcementBarAllocationType { SINGLE, DOUBLE, ALTERNATE, OTHER, USERDEFINED, NOTDEFINED };
	public enum PEnum_ReinforcementBarType { RING, SPIRAL, OTHER, USERDEFINED, NOTDEFINED };
	public enum PEnum_SpaceHeaterConvectorType { FORCED, NATURAL, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_SpaceHeaterPlacementType { BASEBOARD, TOWELWARMER, SUSPENDED, WALL, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_SpaceHeaterRadiatorType { FINNEDTUBE, PANEL, SECTIONAL, TUBULAR, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_SpaceHeaterTemperatureClassification { LOWTEMPERATURE, HIGHTEMPERATURE, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_SpaceHeaterHeatTransferDimension { POINT, PATH, SURFACE, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_SpaceHeaterHeatTransferMedium { WATER, STEAM, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_TaskCategory { ADJUSTMENT, CALIBRATION, EMERGENCY, INSPECTION, OPERATION, PM, SAFETY, SHUTDOWN, STARTUP, TESTING, TROUBLE };
	public enum PEnum_TaskStatus { NOT_YET_STARTED, STARTED, COMPLETED };
	public enum PEnum_ValveMechanism { BALL, BUTTERFLY, CONFIGUREDGATE, GLAND, GLOBE, LUBRICATEDPLUG, NEEDLE, PARALLELSLIDE, PLUG, WEDGEGATE, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_ValveOperation { DROPWEIGHT, FLOAT, HYDRAULIC, LEVER, LOCKSHIELD, MOTORIZED, PNEUMATIC, SOLENOID, SPRING, THERMOSTATIC, WHEEL, OTHER, NOTKNOWN, UNSET };
	public enum PEnum_ValvePattern { SINGLEPORT, ANGLED_2_PORT, STRAIGHT_2_PORT, STRAIGHT_3_PORT, CROSSOVER_4_PORT, OTHER, NOTKNOWN, UNSET };
}
